services:
  q3eded_service:
    image: myq3srv
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      FS_GAME: ${FS_GAME:-baseq3}
      PORT: ${PORT:-27960}
      RCONPASSWORD: ${RCONPASSWORD:-Password123!}
      DEDICATED: ${DEDICATED:-2}
      SERVER_CFG: ${SERVER_CFG:-server.cfg}
    ports:
      - "${PORT}:27960/udp"
    volumes:
      - "${PWD}/${FS_GAME}:/home/q3user_svc/.q3a/${FS_GAME}/"
      - "${PWD}/baseq3:/home/q3user_svc/.q3a/baseq3/"
      - "${PWD}/launcher.sh:/home/q3user_svc/.q3a/launcher.sh"
